name: Azure Static Web Apps CI/CD

on:
  push:
    paths:
      - 'MJExplorer/**'
      - 'GeneratedEntities/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Create environment file
        run: |
          mkdir -p ./src/environments # Ensure the directory exists
          cat << EOF > ./src/environments/environment.ts          
          export const environment = {
            GRAPHQL_URI: '${{ secrets.GRAPHQL_URI }}',
            GRAPHQL_WS_URI: '${{ secrets.GRAPHQL_WS_URI }}',
            REDIRECT_URI: '${{ secrets.REDIRECT_URI }}',
            CLIENT_ID: '${{ secrets.CLIENT_ID }}',
            TENANT_ID: '${{ secrets.TENANT_ID }}',
            CLIENT_AUTHORITY: '${{ secrets.CLIENT_AUTHORITY }}',
            AUTH_TYPE: '${{ secrets.AUTH_TYPE }}',
            NODE_ENV: '${{ secrets.NODE_ENV }}',
            AUTOSAVE_DEBOUNCE_MS: 1200,
            SEARCH_DEBOUNCE_MS: 800,
            MIN_SEARCH_LENGTH: 3,
            MJ_CORE_SCHEMA_NAME: '${{ secrets.MJ_CORE_SCHEMA_NAME }}',
            production: true,
            APPLICATION_NAME: '${{ secrets.APPLICATION_NAME }}',
            APPLICATION_INSTANCE: '${{ secrets.APPLICATION_INSTANCE }}',
            AUTH0_DOMAIN: '${{ secrets.AUTH0_DOMAIN }}',
            AUTH0_CLIENTID: '${{ secrets.AUTH0_CLIENTID }}'
          };
          EOF
        working-directory: MJExplorer

      - name: npm install and build
        run: |
          npm install
          npm run generated
          npm run build --if-present
        working-directory: MJExplorer

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_CLIFF_039E6590F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "MJExplorer" # App source code path
          api_location: "MJAPI" # Api source code path - optional
          output_location: "dist/angular-uitest" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
