# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Demo MJExplorer - mj-mj-demo-mjexplorer

on:
  push:
    paths:
      - 'MJExplorer/**'
      - 'GeneratedEntities/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Create environment file
        run: |
          mkdir -p ./src/environments # Ensure the directory exists
          cat << EOF > ./src/environments/environment.ts
          export const environment = {
            GRAPHQL_URI: '${{ secrets.GRAPHQL_URI }}',
            GRAPHQL_WS_URI: '${{ secrets.GRAPHQL_WS_URI }}',
            REDIRECT_URI: '${{ secrets.REDIRECT_URI }}',
            CLIENT_ID: '${{ secrets.CLIENT_ID }}',
            TENANT_ID: '${{ secrets.TENANT_ID }}',
            CLIENT_AUTHORITY: '${{ secrets.CLIENT_AUTHORITY }}',
            AUTH_TYPE: '${{ secrets.AUTH_TYPE }}',
            NODE_ENV: '${{ secrets.NODE_ENV }}',
            AUTOSAVE_DEBOUNCE_MS: '${{ secrets.AUTOSAVE_DEBOUNCE_MS }}',
            SEARCH_DEBOUNCE_MS: '${{ secrets.SEARCH_DEBOUNCE_MS }}',
            MIN_SEARCH_LENGTH: '${{ secrets.MIN_SEARCH_LENGTH }}',
            MJ_CORE_SCHEMA_NAME: '${{ secrets.MJ_CORE_SCHEMA_NAME }}',
            production: '${{ secrets.production }}',
            APPLICATION_NAME: '${{ secrets.APPLICATION_NAME }}',
            APPLICATION_INSTANCE: '${{ secrets.APPLICATION_INSTANCE }}',
            AUTH0_DOMAIN: '${{ secrets.AUTH0_DOMAIN }}',
            AUTH0_CLIENTID: '${{ secrets.AUTH0_CLIENTID }}'
          };
          EOF
        working-directory: MJExplorer


      - name: npm install, build, and test
        run: |
          npm install
          npm run generated
          npm run build --if-present
          npm run test --if-present
        working-directory: MJExplorer

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: MJExplorer

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: MJExplorer/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mj-mj-demo-mjexplorer'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9D6EA25B059946E0B6DC8F3363DC5B58 }}
